### ISSUE TITLE
TP-LINK WN-725 (RTL8188EUS)

### ISSUE THREAD

**Issue by ghost** [MX-Linux/mx-network-assistant#2]
The performance and reliability are terrible. The signal strength is always reported to be weak even though it's always full on Windows. The download speed is terrible. `apt full-upgrade` and `git clone` are very slow. Even loading of websites in Firefox is slow.

There is no such problem on Windows.

**Comment by AdrianTM** [comment]
No an issue with this mx-network-assistant program, please report Linux support issue to the vendor of the device.
